// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: core/grow/v1beta1/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the grow module's genesis state.
type GenesisState struct {
	Params                    Params       `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	GTokenPairList            []GTokenPair `protobuf:"bytes,2,rep,name=gTokenPairList,proto3" json:"gTokenPairList"`
	RealRate                  uint64       `protobuf:"varint,3,opt,name=RealRate,proto3" json:"RealRate,omitempty"`
	BorrowRate                uint64       `protobuf:"varint,4,opt,name=BorrowRate,proto3" json:"BorrowRate,omitempty"`
	GrowStakingReserveAddress string       `protobuf:"bytes,5,opt,name=GrowStakingReserveAddress,proto3" json:"GrowStakingReserveAddress,omitempty"`
	USQReserveAddress         string       `protobuf:"bytes,6,opt,name=USQReserveAddress,proto3" json:"USQReserveAddress,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_c399ada9d9d9a327, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetGTokenPairList() []GTokenPair {
	if m != nil {
		return m.GTokenPairList
	}
	return nil
}

func (m *GenesisState) GetRealRate() uint64 {
	if m != nil {
		return m.RealRate
	}
	return 0
}

func (m *GenesisState) GetBorrowRate() uint64 {
	if m != nil {
		return m.BorrowRate
	}
	return 0
}

func (m *GenesisState) GetGrowStakingReserveAddress() string {
	if m != nil {
		return m.GrowStakingReserveAddress
	}
	return ""
}

func (m *GenesisState) GetUSQReserveAddress() string {
	if m != nil {
		return m.USQReserveAddress
	}
	return ""
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "core.grow.v1beta1.GenesisState")
}

func init() { proto.RegisterFile("core/grow/v1beta1/genesis.proto", fileDescriptor_c399ada9d9d9a327) }

var fileDescriptor_c399ada9d9d9a327 = []byte{
	// 330 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xb1, 0x4e, 0x2a, 0x41,
	0x18, 0x85, 0x77, 0x80, 0x4b, 0xee, 0x1d, 0x6e, 0x4c, 0x98, 0x58, 0x2c, 0x1b, 0x1d, 0x36, 0x56,
	0x5b, 0x98, 0xdd, 0x80, 0x85, 0x8d, 0x8d, 0xdb, 0x50, 0x68, 0x22, 0x2c, 0xda, 0xd8, 0x0d, 0xf0,
	0x67, 0xdc, 0x20, 0x0c, 0xf9, 0x67, 0x00, 0x7d, 0x0b, 0x1f, 0xc8, 0x07, 0xa0, 0xa4, 0xb4, 0x32,
	0x06, 0x5e, 0xc4, 0x30, 0xbb, 0x51, 0x03, 0xd8, 0xed, 0xce, 0xf7, 0x9d, 0x33, 0x93, 0x1c, 0x5a,
	0xef, 0x2b, 0x84, 0x48, 0xa2, 0x9a, 0x47, 0xb3, 0x46, 0x0f, 0x8c, 0x68, 0x44, 0x12, 0xc6, 0xa0,
	0x53, 0x1d, 0x4e, 0x50, 0x19, 0xc5, 0xaa, 0x1b, 0x21, 0xdc, 0x08, 0x61, 0x2e, 0x78, 0x87, 0x52,
	0x49, 0x65, 0x69, 0xb4, 0xf9, 0xca, 0x44, 0x8f, 0xef, 0x36, 0x4d, 0x04, 0x8a, 0x51, 0x5e, 0xe4,
	0x1d, 0xed, 0xe3, 0x29, 0x66, 0xf4, 0xe4, 0xb5, 0x40, 0xff, 0xb7, 0xb2, 0x8b, 0xbb, 0x46, 0x18,
	0x60, 0xe7, 0xb4, 0x9c, 0xc5, 0x5d, 0xe2, 0x93, 0xa0, 0xd2, 0xac, 0x85, 0x3b, 0x0f, 0x09, 0xdb,
	0x56, 0x88, 0x4b, 0x8b, 0xf7, 0xba, 0x93, 0xe4, 0x3a, 0xbb, 0xa2, 0x07, 0xf2, 0x56, 0x0d, 0x61,
	0xdc, 0x16, 0x29, 0x5e, 0xa7, 0xda, 0xb8, 0x05, 0xbf, 0x18, 0x54, 0x9a, 0xc7, 0x7b, 0x0a, 0xbe,
	0xc5, 0xbc, 0x64, 0x2b, 0xca, 0x3c, 0xfa, 0x37, 0x01, 0xf1, 0x98, 0x08, 0x03, 0x6e, 0xd1, 0x27,
	0x41, 0x29, 0xf9, 0xfa, 0x67, 0x9c, 0xd2, 0x58, 0x21, 0xaa, 0xb9, 0xa5, 0x25, 0x4b, 0x7f, 0x9c,
	0xb0, 0x0b, 0x5a, 0x6b, 0xa1, 0x9a, 0x77, 0x8d, 0x18, 0xa6, 0x63, 0x99, 0x80, 0x06, 0x9c, 0xc1,
	0xe5, 0x60, 0x80, 0xa0, 0xb5, 0xfb, 0xc7, 0x27, 0xc1, 0xbf, 0xe4, 0x77, 0x81, 0x9d, 0xd2, 0xea,
	0x5d, 0xb7, 0xb3, 0x95, 0x2a, 0xdb, 0xd4, 0x2e, 0x88, 0xe3, 0xc5, 0x8a, 0x93, 0xe5, 0x8a, 0x93,
	0x8f, 0x15, 0x27, 0x2f, 0x6b, 0xee, 0x2c, 0xd7, 0xdc, 0x79, 0x5b, 0x73, 0xe7, 0x3e, 0x90, 0xa9,
	0x79, 0x98, 0xf6, 0xc2, 0xbe, 0x1a, 0x45, 0x9d, 0xa9, 0x18, 0xa0, 0x30, 0x70, 0x83, 0x32, 0xb2,
	0x6b, 0x3c, 0x65, 0x7b, 0x98, 0xe7, 0x09, 0xe8, 0x5e, 0xd9, 0x2e, 0x71, 0xf6, 0x19, 0x00, 0x00,
	0xff, 0xff, 0xb0, 0x36, 0x3a, 0xd9, 0x13, 0x02, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.USQReserveAddress) > 0 {
		i -= len(m.USQReserveAddress)
		copy(dAtA[i:], m.USQReserveAddress)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.USQReserveAddress)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.GrowStakingReserveAddress) > 0 {
		i -= len(m.GrowStakingReserveAddress)
		copy(dAtA[i:], m.GrowStakingReserveAddress)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.GrowStakingReserveAddress)))
		i--
		dAtA[i] = 0x2a
	}
	if m.BorrowRate != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.BorrowRate))
		i--
		dAtA[i] = 0x20
	}
	if m.RealRate != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.RealRate))
		i--
		dAtA[i] = 0x18
	}
	if len(m.GTokenPairList) > 0 {
		for iNdEx := len(m.GTokenPairList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.GTokenPairList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.GTokenPairList) > 0 {
		for _, e := range m.GTokenPairList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.RealRate != 0 {
		n += 1 + sovGenesis(uint64(m.RealRate))
	}
	if m.BorrowRate != 0 {
		n += 1 + sovGenesis(uint64(m.BorrowRate))
	}
	l = len(m.GrowStakingReserveAddress)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.USQReserveAddress)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GTokenPairList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GTokenPairList = append(m.GTokenPairList, GTokenPair{})
			if err := m.GTokenPairList[len(m.GTokenPairList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RealRate", wireType)
			}
			m.RealRate = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RealRate |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BorrowRate", wireType)
			}
			m.BorrowRate = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BorrowRate |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GrowStakingReserveAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GrowStakingReserveAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field USQReserveAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.USQReserveAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
