// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: core/stable/v1beta1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	types "github.com/cosmos/cosmos-sdk/x/bank/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	grpc1 "github.com/gogo/protobuf/grpc" 
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa27cebbde0ca0fb, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

type QueryParamsResponse struct {
	ReserveFundAddress string `protobuf:"bytes,1,opt,name=ReserveFundAddress,proto3" json:"ReserveFundAddress,omitempty"`
	BurningFundAddress string `protobuf:"bytes,2,opt,name=BurningFundAddress,proto3" json:"BurningFundAddress,omitempty"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa27cebbde0ca0fb, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetReserveFundAddress() string {
	if m != nil {
		return m.ReserveFundAddress
	}
	return ""
}

func (m *QueryParamsResponse) GetBurningFundAddress() string {
	if m != nil {
		return m.BurningFundAddress
	}
	return ""
}

type PairByPairIdRequest struct {
	PairId string `protobuf:"bytes,1,opt,name=pairId,proto3" json:"pairId,omitempty"`
}

func (m *PairByPairIdRequest) Reset()         { *m = PairByPairIdRequest{} }
func (m *PairByPairIdRequest) String() string { return proto.CompactTextString(m) }
func (*PairByPairIdRequest) ProtoMessage()    {}
func (*PairByPairIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa27cebbde0ca0fb, []int{2}
}
func (m *PairByPairIdRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PairByPairIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PairByPairIdRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PairByPairIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PairByPairIdRequest.Merge(m, src)
}
func (m *PairByPairIdRequest) XXX_Size() int {
	return m.Size()
}
func (m *PairByPairIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PairByPairIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PairByPairIdRequest proto.InternalMessageInfo

func (m *PairByPairIdRequest) GetPairId() string {
	if m != nil {
		return m.PairId
	}
	return ""
}

type PairByIdRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *PairByIdRequest) Reset()         { *m = PairByIdRequest{} }
func (m *PairByIdRequest) String() string { return proto.CompactTextString(m) }
func (*PairByIdRequest) ProtoMessage()    {}
func (*PairByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa27cebbde0ca0fb, []int{3}
}
func (m *PairByIdRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PairByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PairByIdRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PairByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PairByIdRequest.Merge(m, src)
}
func (m *PairByIdRequest) XXX_Size() int {
	return m.Size()
}
func (m *PairByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PairByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PairByIdRequest proto.InternalMessageInfo

func (m *PairByIdRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetAmountOutByAmountInRequest struct {
	PairId   string `protobuf:"bytes,1,opt,name=pairId,proto3" json:"pairId,omitempty"`
	AmountIn uint64 `protobuf:"varint,2,opt,name=amountIn,proto3" json:"amountIn,omitempty"`
	Action   string `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
}

func (m *GetAmountOutByAmountInRequest) Reset()         { *m = GetAmountOutByAmountInRequest{} }
func (m *GetAmountOutByAmountInRequest) String() string { return proto.CompactTextString(m) }
func (*GetAmountOutByAmountInRequest) ProtoMessage()    {}
func (*GetAmountOutByAmountInRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa27cebbde0ca0fb, []int{4}
}
func (m *GetAmountOutByAmountInRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetAmountOutByAmountInRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetAmountOutByAmountInRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetAmountOutByAmountInRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAmountOutByAmountInRequest.Merge(m, src)
}
func (m *GetAmountOutByAmountInRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetAmountOutByAmountInRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAmountOutByAmountInRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAmountOutByAmountInRequest proto.InternalMessageInfo

func (m *GetAmountOutByAmountInRequest) GetPairId() string {
	if m != nil {
		return m.PairId
	}
	return ""
}

func (m *GetAmountOutByAmountInRequest) GetAmountIn() uint64 {
	if m != nil {
		return m.AmountIn
	}
	return 0
}

func (m *GetAmountOutByAmountInRequest) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

type GetAmountOutByAmountInResponse struct {
	PairId    string `protobuf:"bytes,1,opt,name=pairId,proto3" json:"pairId,omitempty"`
	AmountOut uint64 `protobuf:"varint,2,opt,name=amountOut,proto3" json:"amountOut,omitempty"`
	Action    string `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
}

func (m *GetAmountOutByAmountInResponse) Reset()         { *m = GetAmountOutByAmountInResponse{} }
func (m *GetAmountOutByAmountInResponse) String() string { return proto.CompactTextString(m) }
func (*GetAmountOutByAmountInResponse) ProtoMessage()    {}
func (*GetAmountOutByAmountInResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa27cebbde0ca0fb, []int{5}
}
func (m *GetAmountOutByAmountInResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetAmountOutByAmountInResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetAmountOutByAmountInResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetAmountOutByAmountInResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAmountOutByAmountInResponse.Merge(m, src)
}
func (m *GetAmountOutByAmountInResponse) XXX_Size() int {
	return m.Size()
}
func (m *GetAmountOutByAmountInResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAmountOutByAmountInResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAmountOutByAmountInResponse proto.InternalMessageInfo

func (m *GetAmountOutByAmountInResponse) GetPairId() string {
	if m != nil {
		return m.PairId
	}
	return ""
}

func (m *GetAmountOutByAmountInResponse) GetAmountOut() uint64 {
	if m != nil {
		return m.AmountOut
	}
	return 0
}

func (m *GetAmountOutByAmountInResponse) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

type PairRequestResponse struct {
	PairId            string                                 `protobuf:"bytes,1,opt,name=pairId,proto3" json:"pairId,omitempty"`
	AmountInMetadata  types.Metadata                         `protobuf:"bytes,2,opt,name=amountInMetadata,proto3" json:"amountInMetadata" yaml:"amountInMetadata"`
	AmountOutMetadata types.Metadata                         `protobuf:"bytes,3,opt,name=amountOutMetadata,proto3" json:"amountOutMetadata" yaml:"amountOutMetadata"`
	Qm                github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,4,opt,name=qm,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"qm" yaml:"qm"`
	Ar                github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,5,opt,name=ar,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"ar" yaml:"ar"`
	MinAmountIn       string                                 `protobuf:"bytes,6,opt,name=minAmountIn,proto3" json:"minAmountIn,omitempty"`
	MinAmountOut      string                                 `protobuf:"bytes,7,opt,name=minAmountOut,proto3" json:"minAmountOut,omitempty"`
	BackingRatio      uint64                                 `protobuf:"varint,9,opt,name=backing_ratio,json=backingRatio,proto3" json:"backing_ratio,omitempty"`
	MintingFee        uint64                                 `protobuf:"varint,10,opt,name=minting_fee,json=mintingFee,proto3" json:"minting_fee,omitempty"`
	BurningFee        uint64                                 `protobuf:"varint,11,opt,name=burning_fee,json=burningFee,proto3" json:"burning_fee,omitempty"`
}

func (m *PairRequestResponse) Reset()         { *m = PairRequestResponse{} }
func (m *PairRequestResponse) String() string { return proto.CompactTextString(m) }
func (*PairRequestResponse) ProtoMessage()    {}
func (*PairRequestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa27cebbde0ca0fb, []int{6}
}
func (m *PairRequestResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PairRequestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PairRequestResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PairRequestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PairRequestResponse.Merge(m, src)
}
func (m *PairRequestResponse) XXX_Size() int {
	return m.Size()
}
func (m *PairRequestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PairRequestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PairRequestResponse proto.InternalMessageInfo

func (m *PairRequestResponse) GetPairId() string {
	if m != nil {
		return m.PairId
	}
	return ""
}

func (m *PairRequestResponse) GetAmountInMetadata() types.Metadata {
	if m != nil {
		return m.AmountInMetadata
	}
	return types.Metadata{}
}

func (m *PairRequestResponse) GetAmountOutMetadata() types.Metadata {
	if m != nil {
		return m.AmountOutMetadata
	}
	return types.Metadata{}
}

func (m *PairRequestResponse) GetMinAmountIn() string {
	if m != nil {
		return m.MinAmountIn
	}
	return ""
}

func (m *PairRequestResponse) GetMinAmountOut() string {
	if m != nil {
		return m.MinAmountOut
	}
	return ""
}

func (m *PairRequestResponse) GetBackingRatio() uint64 {
	if m != nil {
		return m.BackingRatio
	}
	return 0
}

func (m *PairRequestResponse) GetMintingFee() uint64 {
	if m != nil {
		return m.MintingFee
	}
	return 0
}

func (m *PairRequestResponse) GetBurningFee() uint64 {
	if m != nil {
		return m.BurningFee
	}
	return 0
}

type AmountOutResponse struct {
	PairId    string `protobuf:"bytes,1,opt,name=pairId,proto3" json:"pairId,omitempty"`
	AmountOut uint64 `protobuf:"varint,2,opt,name=amountOut,proto3" json:"amountOut,omitempty"`
	Denom     string `protobuf:"bytes,3,opt,name=denom,proto3" json:"denom,omitempty"`
}

func (m *AmountOutResponse) Reset()         { *m = AmountOutResponse{} }
func (m *AmountOutResponse) String() string { return proto.CompactTextString(m) }
func (*AmountOutResponse) ProtoMessage()    {}
func (*AmountOutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa27cebbde0ca0fb, []int{7}
}
func (m *AmountOutResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AmountOutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AmountOutResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AmountOutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AmountOutResponse.Merge(m, src)
}
func (m *AmountOutResponse) XXX_Size() int {
	return m.Size()
}
func (m *AmountOutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AmountOutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AmountOutResponse proto.InternalMessageInfo

func (m *AmountOutResponse) GetPairId() string {
	if m != nil {
		return m.PairId
	}
	return ""
}

func (m *AmountOutResponse) GetAmountOut() uint64 {
	if m != nil {
		return m.AmountOut
	}
	return 0
}

func (m *AmountOutResponse) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

type AllPairsRequest struct {
}

func (m *AllPairsRequest) Reset()         { *m = AllPairsRequest{} }
func (m *AllPairsRequest) String() string { return proto.CompactTextString(m) }
func (*AllPairsRequest) ProtoMessage()    {}
func (*AllPairsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa27cebbde0ca0fb, []int{8}
}
func (m *AllPairsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AllPairsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AllPairsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AllPairsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllPairsRequest.Merge(m, src)
}
func (m *AllPairsRequest) XXX_Size() int {
	return m.Size()
}
func (m *AllPairsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AllPairsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AllPairsRequest proto.InternalMessageInfo

type AllPairsResponse struct {
	Pairs []*Pair `protobuf:"bytes,1,rep,name=pairs,proto3" json:"pairs,omitempty"`
}

func (m *AllPairsResponse) Reset()         { *m = AllPairsResponse{} }
func (m *AllPairsResponse) String() string { return proto.CompactTextString(m) }
func (*AllPairsResponse) ProtoMessage()    {}
func (*AllPairsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa27cebbde0ca0fb, []int{9}
}
func (m *AllPairsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AllPairsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AllPairsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AllPairsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllPairsResponse.Merge(m, src)
}
func (m *AllPairsResponse) XXX_Size() int {
	return m.Size()
}
func (m *AllPairsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AllPairsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AllPairsResponse proto.InternalMessageInfo

func (m *AllPairsResponse) GetPairs() []*Pair {
	if m != nil {
		return m.Pairs
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "core.stable.v1beta1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "core.stable.v1beta1.QueryParamsResponse")
	proto.RegisterType((*PairByPairIdRequest)(nil), "core.stable.v1beta1.PairByPairIdRequest")
	proto.RegisterType((*PairByIdRequest)(nil), "core.stable.v1beta1.PairByIdRequest")
	proto.RegisterType((*GetAmountOutByAmountInRequest)(nil), "core.stable.v1beta1.GetAmountOutByAmountInRequest")
	proto.RegisterType((*GetAmountOutByAmountInResponse)(nil), "core.stable.v1beta1.GetAmountOutByAmountInResponse")
	proto.RegisterType((*PairRequestResponse)(nil), "core.stable.v1beta1.PairRequestResponse")
	proto.RegisterType((*AmountOutResponse)(nil), "core.stable.v1beta1.AmountOutResponse")
	proto.RegisterType((*AllPairsRequest)(nil), "core.stable.v1beta1.AllPairsRequest")
	proto.RegisterType((*AllPairsResponse)(nil), "core.stable.v1beta1.AllPairsResponse")
}

func init() { proto.RegisterFile("core/stable/v1beta1/query.proto", fileDescriptor_fa27cebbde0ca0fb) }

var fileDescriptor_fa27cebbde0ca0fb = []byte{
	// 841 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0x4d, 0x6f, 0xe3, 0x44,
	0x18, 0x8e, 0xd3, 0x24, 0x34, 0x93, 0xc2, 0x6e, 0xa7, 0xd5, 0x62, 0x4c, 0xeb, 0x84, 0xd9, 0x65,
	0x89, 0x2a, 0xad, 0xad, 0xcd, 0xde, 0xe0, 0xd4, 0x80, 0x0a, 0x05, 0xa1, 0xed, 0xfa, 0xc8, 0xa5,
	0x9a, 0xc4, 0x83, 0x31, 0x89, 0xc7, 0x89, 0x3d, 0xae, 0x88, 0xaa, 0x4a, 0xa8, 0x3f, 0x00, 0x21,
	0xf1, 0xa7, 0x7a, 0xa3, 0x52, 0x2f, 0x88, 0x43, 0x84, 0x5a, 0x7e, 0x41, 0xf9, 0x03, 0x68, 0x3e,
	0xec, 0xa4, 0x89, 0xdd, 0xc0, 0xf6, 0x92, 0xcc, 0xbc, 0xef, 0x33, 0xef, 0xf3, 0xcc, 0xcc, 0x3b,
	0x4f, 0x02, 0x9a, 0xfd, 0x30, 0x22, 0x76, 0xcc, 0x70, 0x6f, 0x48, 0xec, 0x93, 0x97, 0x3d, 0xc2,
	0xf0, 0x4b, 0x7b, 0x9c, 0x90, 0x68, 0x62, 0x8d, 0xa2, 0x90, 0x85, 0x70, 0x8b, 0x03, 0x2c, 0x09,
	0xb0, 0x14, 0xc0, 0xd8, 0xf6, 0x42, 0x2f, 0x14, 0x79, 0x9b, 0x8f, 0x24, 0xd4, 0xd8, 0xf1, 0xc2,
	0xd0, 0x1b, 0x12, 0x1b, 0x8f, 0x7c, 0x1b, 0x53, 0x1a, 0x32, 0xcc, 0xfc, 0x90, 0xc6, 0x2a, 0xbb,
	0xd7, 0x0f, 0xe3, 0x20, 0x8c, 0xed, 0x1e, 0x8e, 0x89, 0x64, 0xc8, 0xf8, 0x46, 0xd8, 0xf3, 0xa9,
	0x00, 0x2b, 0xac, 0x99, 0xa7, 0x6a, 0x84, 0xfd, 0x68, 0x96, 0x57, 0xb5, 0xe8, 0x20, 0xcb, 0xf3,
	0x89, 0xcc, 0xa3, 0x6d, 0x00, 0xdf, 0x70, 0x86, 0x23, 0x1c, 0xe1, 0x20, 0x76, 0xc8, 0x38, 0x21,
	0x31, 0x43, 0x09, 0xd8, 0xba, 0x13, 0x8d, 0x47, 0x21, 0x8d, 0x09, 0xb4, 0x00, 0x74, 0x48, 0x4c,
	0xa2, 0x13, 0x72, 0x90, 0x50, 0x77, 0xdf, 0x75, 0x23, 0x12, 0xc7, 0xba, 0xd6, 0xd2, 0xda, 0x75,
	0x27, 0x27, 0xc3, 0xf1, 0xdd, 0x24, 0xa2, 0x3e, 0xf5, 0xe6, 0xf1, 0x65, 0x89, 0x5f, 0xce, 0xa0,
	0x17, 0x60, 0xeb, 0x08, 0xfb, 0x51, 0x77, 0xc2, 0x3f, 0x0f, 0x5d, 0xa5, 0x06, 0x3e, 0x01, 0xb5,
	0x91, 0x08, 0x28, 0x2a, 0x35, 0x43, 0x1f, 0x81, 0x47, 0x12, 0x3e, 0x83, 0xbe, 0x07, 0xca, 0xbe,
	0x84, 0x55, 0x9c, 0xb2, 0xef, 0xa2, 0x01, 0xd8, 0xfd, 0x92, 0xb0, 0xfd, 0x20, 0x4c, 0x28, 0x7b,
	0x9d, 0xb0, 0xee, 0x44, 0x0e, 0x0f, 0xe9, 0x8a, 0xda, 0xd0, 0x00, 0xeb, 0x58, 0x41, 0x85, 0xe0,
	0x8a, 0x93, 0xcd, 0xf9, 0x1a, 0xdc, 0xe7, 0x77, 0xa0, 0xaf, 0xc9, 0x35, 0x72, 0x86, 0x28, 0x30,
	0x8b, 0xc8, 0xd4, 0x01, 0x16, 0xb1, 0xed, 0x80, 0x3a, 0x4e, 0x97, 0x29, 0xba, 0x59, 0xa0, 0x90,
	0xef, 0xf7, 0x8a, 0x3c, 0x2f, 0xb5, 0x97, 0x95, 0x2c, 0x3f, 0x82, 0xc7, 0xe9, 0x1e, 0xbe, 0x25,
	0x0c, 0xbb, 0x98, 0x61, 0x41, 0xd6, 0xe8, 0xec, 0x5a, 0xb2, 0x4d, 0x2c, 0xd1, 0x19, 0xaa, 0x4d,
	0xac, 0x14, 0xd4, 0x6d, 0x5e, 0x4c, 0x9b, 0xa5, 0xdb, 0x69, 0xf3, 0xfd, 0x09, 0x0e, 0x86, 0x9f,
	0xa2, 0xc5, 0x22, 0xc8, 0x59, 0xaa, 0x0b, 0x03, 0xb0, 0x99, 0x6d, 0x20, 0x23, 0x5b, 0xfb, 0x2f,
	0x64, 0x2d, 0x45, 0xa6, 0xcf, 0x93, 0xcd, 0x55, 0x41, 0xce, 0x72, 0x65, 0xf8, 0x0d, 0x28, 0x8f,
	0x03, 0xbd, 0xc2, 0xb7, 0xdb, 0xfd, 0x8c, 0x17, 0xf8, 0x73, 0xda, 0x7c, 0xee, 0xf9, 0xec, 0x87,
	0xa4, 0x67, 0xf5, 0xc3, 0xc0, 0x56, 0xaf, 0x40, 0x7e, 0xbd, 0x88, 0xdd, 0x81, 0xcd, 0x26, 0x23,
	0x12, 0x5b, 0x87, 0x94, 0xdd, 0x4e, 0x9b, 0x75, 0x49, 0x35, 0x0e, 0x90, 0x53, 0x1e, 0x07, 0xbc,
	0x18, 0x8e, 0xf4, 0xea, 0xc3, 0x8a, 0xe1, 0x08, 0x39, 0x65, 0x1c, 0xc1, 0x16, 0x68, 0x04, 0x3e,
	0x4d, 0x3b, 0x41, 0xaf, 0x89, 0x1b, 0x99, 0x0f, 0x41, 0x04, 0x36, 0xb2, 0x29, 0xbf, 0xff, 0x77,
	0x04, 0xe4, 0x4e, 0x0c, 0x3e, 0x05, 0xef, 0xf6, 0x70, 0x7f, 0xe0, 0x53, 0xef, 0x38, 0xe2, 0xcf,
	0x5f, 0xaf, 0x8b, 0x26, 0xd9, 0x50, 0x41, 0x87, 0xc7, 0x60, 0x53, 0x50, 0x31, 0x0e, 0xfa, 0x9e,
	0x10, 0x1d, 0x08, 0x08, 0x50, 0xa1, 0x03, 0x42, 0x38, 0xa0, 0x27, 0x5f, 0x9d, 0x00, 0x34, 0x24,
	0x40, 0x85, 0x0e, 0x08, 0x41, 0xc7, 0x60, 0x33, 0xe3, 0x7c, 0x60, 0xd3, 0x6e, 0x83, 0xaa, 0x4b,
	0x68, 0x18, 0xa8, 0x9e, 0x95, 0x13, 0xb4, 0x09, 0x1e, 0xed, 0x0f, 0x87, 0xbc, 0x69, 0x33, 0xaf,
	0xf9, 0x1c, 0x3c, 0x9e, 0x85, 0x14, 0xa5, 0x0d, 0xaa, 0x9c, 0x84, 0x7b, 0xcb, 0x5a, 0xbb, 0xd1,
	0xf9, 0xc0, 0xca, 0xb1, 0x56, 0x4b, 0xb4, 0xbe, 0xc4, 0x75, 0xfe, 0xa9, 0x82, 0xaa, 0x70, 0x2c,
	0xf8, 0xb3, 0x06, 0x6a, 0xd2, 0xb6, 0xe0, 0x27, 0xb9, 0xcb, 0x96, 0xed, 0xce, 0x68, 0xaf, 0x06,
	0x4a, 0x61, 0xe8, 0xe9, 0xf9, 0xd5, 0xdf, 0xbf, 0x95, 0x77, 0xe1, 0x87, 0x76, 0xbe, 0xef, 0x0a,
	0xde, 0x5f, 0x34, 0xb0, 0x31, 0xef, 0x63, 0xb0, 0x5d, 0xa8, 0x7f, 0xc1, 0xea, 0x8c, 0x62, 0xe4,
	0xc2, 0x23, 0x47, 0x7b, 0x42, 0xc9, 0x33, 0x88, 0xec, 0xa2, 0x5f, 0x00, 0xfb, 0x54, 0x5e, 0xd4,
	0x19, 0x3c, 0xd7, 0xc0, 0x7a, 0xea, 0x94, 0xf0, 0xd9, 0x3d, 0x62, 0xde, 0x46, 0xc8, 0x73, 0x21,
	0xa4, 0x05, 0xcd, 0x7b, 0x84, 0xf8, 0xee, 0x19, 0xbc, 0xd2, 0xc0, 0x93, 0x7c, 0x7b, 0x84, 0x9d,
	0x5c, 0xb2, 0x7b, 0x8d, 0xdb, 0x78, 0xf5, 0xbf, 0xd6, 0x28, 0xad, 0x47, 0x42, 0xeb, 0xd7, 0xf0,
	0xab, 0x5c, 0xad, 0x5e, 0xee, 0xe2, 0xec, 0x18, 0xed, 0xd3, 0xd4, 0xe5, 0xf8, 0x50, 0x58, 0xf0,
	0x19, 0x3c, 0x05, 0xeb, 0x69, 0xf7, 0x16, 0x9c, 0xec, 0x42, 0xbf, 0x1b, 0x1f, 0xaf, 0x40, 0x29,
	0xa9, 0x48, 0x48, 0xdd, 0x81, 0x46, 0xe1, 0xb1, 0xc6, 0xdd, 0x2f, 0x2e, 0xae, 0x4d, 0xed, 0xf2,
	0xda, 0xd4, 0xfe, 0xba, 0x36, 0xb5, 0x5f, 0x6f, 0xcc, 0xd2, 0xe5, 0x8d, 0x59, 0xfa, 0xe3, 0xc6,
	0x2c, 0x7d, 0xb7, 0x37, 0x67, 0x57, 0x6f, 0x12, 0xec, 0x46, 0x98, 0x91, 0xd7, 0x91, 0x27, 0x6b,
	0xfd, 0x94, 0x56, 0x13, 0xb6, 0xd5, 0xab, 0x89, 0x7f, 0x02, 0xaf, 0xfe, 0x0d, 0x00, 0x00, 0xff,
	0xff, 0xfb, 0xf2, 0xf1, 0x28, 0xe1, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	PairByPairId(ctx context.Context, in *PairByPairIdRequest, opts ...grpc.CallOption) (*PairRequestResponse, error)
	PairById(ctx context.Context, in *PairByIdRequest, opts ...grpc.CallOption) (*PairRequestResponse, error)
	GetAmountOutByAmountIn(ctx context.Context, in *GetAmountOutByAmountInRequest, opts ...grpc.CallOption) (*GetAmountOutByAmountInResponse, error)
	AllPairs(ctx context.Context, in *AllPairsRequest, opts ...grpc.CallOption) (*AllPairsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/core.stable.v1beta1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) PairByPairId(ctx context.Context, in *PairByPairIdRequest, opts ...grpc.CallOption) (*PairRequestResponse, error) {
	out := new(PairRequestResponse)
	err := c.cc.Invoke(ctx, "/core.stable.v1beta1.Query/PairByPairId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) PairById(ctx context.Context, in *PairByIdRequest, opts ...grpc.CallOption) (*PairRequestResponse, error) {
	out := new(PairRequestResponse)
	err := c.cc.Invoke(ctx, "/core.stable.v1beta1.Query/PairById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetAmountOutByAmountIn(ctx context.Context, in *GetAmountOutByAmountInRequest, opts ...grpc.CallOption) (*GetAmountOutByAmountInResponse, error) {
	out := new(GetAmountOutByAmountInResponse)
	err := c.cc.Invoke(ctx, "/core.stable.v1beta1.Query/GetAmountOutByAmountIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AllPairs(ctx context.Context, in *AllPairsRequest, opts ...grpc.CallOption) (*AllPairsResponse, error) {
	out := new(AllPairsResponse)
	err := c.cc.Invoke(ctx, "/core.stable.v1beta1.Query/AllPairs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	PairByPairId(context.Context, *PairByPairIdRequest) (*PairRequestResponse, error)
	PairById(context.Context, *PairByIdRequest) (*PairRequestResponse, error)
	GetAmountOutByAmountIn(context.Context, *GetAmountOutByAmountInRequest) (*GetAmountOutByAmountInResponse, error)
	AllPairs(context.Context, *AllPairsRequest) (*AllPairsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) PairByPairId(ctx context.Context, req *PairByPairIdRequest) (*PairRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PairByPairId not implemented")
}
func (*UnimplementedQueryServer) PairById(ctx context.Context, req *PairByIdRequest) (*PairRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PairById not implemented")
}
func (*UnimplementedQueryServer) GetAmountOutByAmountIn(ctx context.Context, req *GetAmountOutByAmountInRequest) (*GetAmountOutByAmountInResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAmountOutByAmountIn not implemented")
}
func (*UnimplementedQueryServer) AllPairs(ctx context.Context, req *AllPairsRequest) (*AllPairsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllPairs not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/core.stable.v1beta1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_PairByPairId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PairByPairIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PairByPairId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/core.stable.v1beta1.Query/PairByPairId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PairByPairId(ctx, req.(*PairByPairIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_PairById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PairByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PairById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/core.stable.v1beta1.Query/PairById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PairById(ctx, req.(*PairByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetAmountOutByAmountIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAmountOutByAmountInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetAmountOutByAmountIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/core.stable.v1beta1.Query/GetAmountOutByAmountIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetAmountOutByAmountIn(ctx, req.(*GetAmountOutByAmountInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AllPairs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllPairsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AllPairs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/core.stable.v1beta1.Query/AllPairs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AllPairs(ctx, req.(*AllPairsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "core.stable.v1beta1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "PairByPairId",
			Handler:    _Query_PairByPairId_Handler,
		},
		{
			MethodName: "PairById",
			Handler:    _Query_PairById_Handler,
		},
		{
			MethodName: "GetAmountOutByAmountIn",
			Handler:    _Query_GetAmountOutByAmountIn_Handler,
		},
		{
			MethodName: "AllPairs",
			Handler:    _Query_AllPairs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "core/stable/v1beta1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.BurningFundAddress) > 0 {
		i -= len(m.BurningFundAddress)
		copy(dAtA[i:], m.BurningFundAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.BurningFundAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ReserveFundAddress) > 0 {
		i -= len(m.ReserveFundAddress)
		copy(dAtA[i:], m.ReserveFundAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ReserveFundAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PairByPairIdRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PairByPairIdRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PairByPairIdRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PairId) > 0 {
		i -= len(m.PairId)
		copy(dAtA[i:], m.PairId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.PairId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PairByIdRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PairByIdRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PairByIdRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *GetAmountOutByAmountInRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetAmountOutByAmountInRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetAmountOutByAmountInRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Action) > 0 {
		i -= len(m.Action)
		copy(dAtA[i:], m.Action)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Action)))
		i--
		dAtA[i] = 0x1a
	}
	if m.AmountIn != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.AmountIn))
		i--
		dAtA[i] = 0x10
	}
	if len(m.PairId) > 0 {
		i -= len(m.PairId)
		copy(dAtA[i:], m.PairId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.PairId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GetAmountOutByAmountInResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetAmountOutByAmountInResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetAmountOutByAmountInResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Action) > 0 {
		i -= len(m.Action)
		copy(dAtA[i:], m.Action)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Action)))
		i--
		dAtA[i] = 0x1a
	}
	if m.AmountOut != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.AmountOut))
		i--
		dAtA[i] = 0x10
	}
	if len(m.PairId) > 0 {
		i -= len(m.PairId)
		copy(dAtA[i:], m.PairId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.PairId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PairRequestResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PairRequestResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PairRequestResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BurningFee != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.BurningFee))
		i--
		dAtA[i] = 0x58
	}
	if m.MintingFee != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.MintingFee))
		i--
		dAtA[i] = 0x50
	}
	if m.BackingRatio != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.BackingRatio))
		i--
		dAtA[i] = 0x48
	}
	if len(m.MinAmountOut) > 0 {
		i -= len(m.MinAmountOut)
		copy(dAtA[i:], m.MinAmountOut)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.MinAmountOut)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.MinAmountIn) > 0 {
		i -= len(m.MinAmountIn)
		copy(dAtA[i:], m.MinAmountIn)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.MinAmountIn)))
		i--
		dAtA[i] = 0x32
	}
	{
		size := m.Ar.Size()
		i -= size
		if _, err := m.Ar.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size := m.Qm.Size()
		i -= size
		if _, err := m.Qm.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size, err := m.AmountOutMetadata.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.AmountInMetadata.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.PairId) > 0 {
		i -= len(m.PairId)
		copy(dAtA[i:], m.PairId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.PairId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *AmountOutResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AmountOutResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AmountOutResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x1a
	}
	if m.AmountOut != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.AmountOut))
		i--
		dAtA[i] = 0x10
	}
	if len(m.PairId) > 0 {
		i -= len(m.PairId)
		copy(dAtA[i:], m.PairId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.PairId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *AllPairsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AllPairsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AllPairsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *AllPairsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AllPairsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AllPairsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Pairs) > 0 {
		for iNdEx := len(m.Pairs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Pairs[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ReserveFundAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.BurningFundAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *PairByPairIdRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.PairId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *PairByIdRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *GetAmountOutByAmountInRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.PairId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.AmountIn != 0 {
		n += 1 + sovQuery(uint64(m.AmountIn))
	}
	l = len(m.Action)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *GetAmountOutByAmountInResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.PairId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.AmountOut != 0 {
		n += 1 + sovQuery(uint64(m.AmountOut))
	}
	l = len(m.Action)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *PairRequestResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.PairId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = m.AmountInMetadata.Size()
	n += 1 + l + sovQuery(uint64(l))
	l = m.AmountOutMetadata.Size()
	n += 1 + l + sovQuery(uint64(l))
	l = m.Qm.Size()
	n += 1 + l + sovQuery(uint64(l))
	l = m.Ar.Size()
	n += 1 + l + sovQuery(uint64(l))
	l = len(m.MinAmountIn)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.MinAmountOut)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.BackingRatio != 0 {
		n += 1 + sovQuery(uint64(m.BackingRatio))
	}
	if m.MintingFee != 0 {
		n += 1 + sovQuery(uint64(m.MintingFee))
	}
	if m.BurningFee != 0 {
		n += 1 + sovQuery(uint64(m.BurningFee))
	}
	return n
}

func (m *AmountOutResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.PairId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.AmountOut != 0 {
		n += 1 + sovQuery(uint64(m.AmountOut))
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *AllPairsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *AllPairsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Pairs) > 0 {
		for _, e := range m.Pairs {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReserveFundAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReserveFundAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BurningFundAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BurningFundAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PairByPairIdRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PairByPairIdRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PairByPairIdRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PairId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PairId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PairByIdRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PairByIdRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PairByIdRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetAmountOutByAmountInRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetAmountOutByAmountInRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetAmountOutByAmountInRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PairId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PairId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AmountIn", wireType)
			}
			m.AmountIn = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AmountIn |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Action", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Action = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetAmountOutByAmountInResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetAmountOutByAmountInResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetAmountOutByAmountInResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PairId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PairId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AmountOut", wireType)
			}
			m.AmountOut = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AmountOut |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Action", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Action = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PairRequestResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PairRequestResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PairRequestResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PairId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PairId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AmountInMetadata", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AmountInMetadata.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AmountOutMetadata", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AmountOutMetadata.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Qm", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Qm.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ar", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Ar.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinAmountIn", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MinAmountIn = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinAmountOut", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MinAmountOut = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BackingRatio", wireType)
			}
			m.BackingRatio = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BackingRatio |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MintingFee", wireType)
			}
			m.MintingFee = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MintingFee |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BurningFee", wireType)
			}
			m.BurningFee = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BurningFee |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AmountOutResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AmountOutResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AmountOutResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PairId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PairId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AmountOut", wireType)
			}
			m.AmountOut = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AmountOut |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AllPairsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AllPairsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AllPairsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AllPairsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AllPairsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AllPairsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pairs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Pairs = append(m.Pairs, &Pair{})
			if err := m.Pairs[len(m.Pairs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
