name: Lint

on: push

jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20.x"
          check-latest: true
      - name: run linting
        run: |
          make lint