name: Qube Upgrade Testing

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build
        run: |
          go mod tidy
          go build ./cmd/qubed/

      - name: Rux upgrade/ tests
        run: go test -v -tags='ledger test_ledger_mock' ./app/upgrades/...
